#!/bin/bash


case "$1" in
    --code)
        flag=0
        if [ "$2" == '-f' ]; then
            filename=$3
            prompt=$4
        elif [ "$3" == '-f' ]; then
            filename= $4
            prompt= $2
        else
            flag=1
            prompt=$2
            prompt=\"${prompt}\"
            commando="${prompt}"
        fi

        file="-f"
        prompt=\"${prompt}\"
        command="${file} ${filename} ${prompt}"

        if [ $flag == 0 ]; then
            python3 /home/theoutlier/Music/hack/CLI-Sage/code.py $command
        else 
            python3 /home/theoutlier/Music/hack/CLI-Sage/code.py "$commando"
        fi
        ;;
    --shell)
        python3 /home/theoutlier/Music/hack/CLI-Sage/command.py 
        ;;
    --debug)
        python3 /home/theoutlier/Music/hack/CLI-Sage/error.py
        ;;
    *)
        python3 /home/theoutlier/Music/hack/CLI-Sage/chat.py $1 
        ;;

esac
